NAME = 		libft.a

SRC = 		ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c \
			ft_isascii.c ft_isdigit.c ft_isprint.c ft_memccpy.c ft_memchr.c \
			ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c ft_strdup.c \
			ft_strjoin.c ft_strlcpy.c ft_strlen.c ft_strncmp.c ft_strnstr.c \
			ft_strrchr.c ft_substr.c ft_tolower.c ft_toupper.c ft_strtrim.c \
			ft_split.c ft_itoa.c ft_strmapi.c ft_putchar_fd.c ft_putstr_fd.c \
			ft_putendl_fd.c ft_putnbr_fd.c ft_strchr.c ft_strlcat.c

BONUS =		ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c \
			ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c

ADD =		ft_intlen.c ft_itoa.c ft_strrev.c ft_putchar.c ft_putstr.c \
			ft_tohexa.c ft_strcmp.c ft_atof.c ft_isfloat.c ft_splitstr.c

CC = 		gcc

CFLAGS = 	-Wall -Wextra -Werror

OBJ = 		$(SRC:.c=.o)

BONUSOBJ =	$(BONUS:.c=.o)

ADDOBJ =	$(ADD:.c=.o)

RM = 		rm -rf

.c.o:
			${CC} ${CFLAGS} -c $< -o ${<:.c=.o}

$(NAME):	${OBJ}
			ar rc ${NAME} ${OBJ}

all: 		${NAME}

bonus:		${OBJ} ${BONUSOBJ}
			ar rc ${NAME} ${OBJ} ${BONUSOBJ}

add:		${OBJ} ${BONUSOBJ} ${ADDOBJ}
			ar rc ${NAME} ${OBJ} ${BONUSOBJ} ${ADDOBJ}

clean:
			${RM} *.o

fclean: 	clean
			${RM} ${NAME}

re: 		fclean all

.PHONY:		all clean fclean re bonus add
